### ISSUE TITLE
Update readme of alpine based images to warn about DNS issue with very long hostnames

### ISSUE THREAD

**Issue by djesic** [green-coding-solutions/example-applications#36]
Images that have alpine:
- idle
- puppeteer chrome/firefox
- stress
- network-test

Idle and stress don't really use any networking, maybe skip those?

Rationale for this issue: https://purplecarrot.co.uk/post/2021-09-04-does_alpine-resolve_dns_properly/

**Comment by ribalba** [comment]
@djesic: Has this been done? 

@ArneTR do you know something about this?

**Comment by djesic** [comment]
@ribalba  Not by me, no.
I was just cleaning up my stale issue backlog about a month ago.
If the work is still necessary, would you please recreate the ticket instead of reopening?
